import { Card } from "./index.js";

export const cards = [
    {
        name: 'red1',
        color: 'red',
        value: 1,
        quantity: 4,
    },
    {
        name: 'red2',
        color: 'red',
        value: 2,
        quantity: 4,
    },
    {
        name: 'red3',
        color: 'red',
        value: 3,
        quantity: 4,
    },
    {
        name: 'red4',
        color: 'red',
        value: 4,
        quantity: 4,
    },
    {
        name: 'red5',
        color: 'red',
        value: 5,
        quantity: 4,
    },
    {
        name: 'red6',
        color: 'red',
        value: 6,
        quantity: 4,
    },
    {
        name: 'red7',
        color: 'red',
        value: 7,
        quantity: 4,
    },
    {
        name: 'green1',
        color: 'green',
        value: 1,
        quantity: 4,
    },
    {
        name: 'green2',
        color: 'green',
        value: 2,
        quantity: 4,
    },
    {
        name: 'green3',
        color: 'green',
        value: 3,
        quantity: 4,
    },
    {
        name: 'green4',
        color: 'green',
        value: 4,
        quantity: 4,
    },
    {
        name: 'green5',
        color: 'green',
        value: 5,
        quantity: 4,
    },
    {
        name: 'green6',
        color: 'green',
        value: 6,
        quantity: 4,
    },
    {
        name: 'green7',
        color: 'green',
        value: 7,
        quantity: 4,
    },
    {
        name: 'blue1',
        color: 'blue',
        value: 1,
        quantity: 4,
    },
    {
        name: 'blue2',
        color: 'blue',
        value: 2,
        quantity: 4,
    },
    {
        name: 'blue3',
        color: 'blue',
        value: 3,
        quantity: 4,
    },
    {
        name: 'blue4',
        color: 'blue',
        value: 4,
        quantity: 4,
    },
    {
        name: 'blue5',
        color: 'blue',
        value: 5,
        quantity: 4,
    },
    {
        name: 'blue6',
        color: 'blue',
        value: 6,
        quantity: 4,
    },
    {
        name: 'blue7',
        color: 'blue',
        value: 7,
        quantity: 4,
    },
    {
        name: 'purple1',
        color: 'purple',
        value: 1,
        quantity: 4,
    },
    {
        name: 'purple2',
        color: 'purple',
        value: 2,
        quantity: 4,
    },
    {
        name: 'purple3',
        color: 'purple',
        value: 3,
        quantity: 4,
    },
    {
        name: 'purple4',
        color: 'purple',
        value: 4,
        quantity: 4,
    },
    {
        name: 'purple5',
        color: 'purple',
        value: 5,
        quantity: 4,
    },
    {
        name: 'purple6',
        color: 'purple',
        value: 6,
        quantity: 4,
    },
    {
        name: 'purple7',
        color: 'purple',
        value: 7,
        quantity: 4,
    },
    {
        name: 'black+1',
        color: 'black',
        value: '+1',
        quantity: 7,
    },
]